# Generated by Django 2.1.3 on 2018-11-11 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vk_id', models.CharField(max_length=100)),
                ('vk_token', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('course_type', models.CharField(choices=[('club', 'club'), ('competition', 'competition'), ('activity', 'activity'), ('unknown', 'unknown')], max_length=200)),
                ('regularity', models.CharField(blank=True, max_length=400, null=True)),
                ('class_start', models.IntegerField(default=5)),
                ('class_end', models.IntegerField(default=11)),
                ('intramuraled', models.CharField(choices=[('intramural', 'intramural'), ('extramural', 'extramural'), ('online', 'online'), ('unknown', 'unknown')], max_length=200)),
                ('command', models.CharField(choices=[('command', 'command'), ('personal', 'personal'), ('unknown', 'unknown')], max_length=200)),
                ('url', models.URLField()),
                ('specialization', models.CharField(choices=[('math', 'math'), ('history', 'history'), ('programming', 'programming'), ('unknown', 'unknown')], max_length=200)),
                ('source', models.CharField(choices=[('admin', 'admin'), ('sirius', 'sirius')], default='admin', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField(blank=True, null=True)),
                ('vk_token', models.CharField(blank=True, max_length=400, null=True)),
                ('sirius_id', models.IntegerField(blank=True, null=True)),
                ('sirius_password', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_token', models.UUIDField(default=uuid.uuid4)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('current_class', models.IntegerField(default=5)),
                ('educational_feed', models.ManyToManyField(blank=True, null=True, related_name='educational_feed_courses', to='api.Course')),
                ('educational_trajectory', models.ManyToManyField(blank=True, null=True, related_name='educational_trajectory_courses', to='api.CourseTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_template',
            field=models.ForeignKey(null=True, on_delete=True, to='api.CourseTemplate'),
        ),
    ]
