# Generated by Django 2.1.3 on 2018-11-10 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vk_id', models.CharField(max_length=100)),
                ('vk_token', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(max_length=100, null=True)),
                ('vk_token', models.CharField(max_length=400, null=True)),
                ('sirius_id', models.IntegerField(blank=True, null=True)),
                ('sirius_password', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_token', models.UUIDField(default=uuid.uuid4)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, default=None, max_length=400, null=True)),
            ],
        ),
    ]
