# Generated by Django 2.1.3 on 2018-11-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='vk_id',
            field=models.IntegerField(null=True),
        ),
    ]
