# Generated by Django 2.1.3 on 2018-11-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fill_sirius_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='hist_possibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='math_possibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='prog_possibility',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
