# Generated by Django 2.1.3 on 2018-11-10 17:21

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('api', '0003_auto_20181110_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vk_id', models.CharField(max_length=100)),
                ('vk_token', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('vk_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('vk_token', models.CharField(max_length=400)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_phone_confirmed', models.BooleanField(default=False)),
                ('email', models.TextField(blank=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('auth_token', models.UUIDField(default=uuid.uuid4)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
            ],
        ),
    ]
