# Generated by Django 2.1.3 on 2018-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adminuser_vkuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='is_email_confirmed',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='is_phone_confirmed',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='point',
        ),
        migrations.AddField(
            model_name='vkuser',
            name='sirius_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='sirius_password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
