# Generated by Django 2.1.3 on 2018-11-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181111_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='current_class',
            field=models.IntegerField(default=5),
        ),
    ]
