# Generated by Django 2.1.3 on 2018-11-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fill_courses'),
        ('api', '0005_auto_20181111_0301'),
    ]

    operations = [
    ]
