# Generated by Django 2.1.3 on 2018-11-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181110_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='sirius_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
