# Generated by Django 2.1.3 on 2018-11-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vkuser_current_class'),
        ('api', '0006_merge_20181111_0355'),
    ]

    operations = [
    ]
