# Generated by Django 2.1.3 on 2018-11-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20181111_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='vk_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
