# Generated by Django 2.1.3 on 2018-11-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181111_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetemplate',
            name='source',
            field=models.CharField(choices=[('admin', 'admin'), ('sirius', 'sirius')], default='admin', max_length=200),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='command',
            field=models.CharField(choices=[('command', 'command'), ('personal', 'personal'), ('unknown', 'unknown')], max_length=200),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='course_type',
            field=models.CharField(choices=[('club', 'club'), ('competition', 'competition'), ('activity', 'activity'), ('unknown', 'unknown')], max_length=200),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='intramuraled',
            field=models.CharField(choices=[('intramural', 'intramural'), ('extramural', 'extramural'), ('online', 'online'), ('unknown', 'unknown')], max_length=200),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='specialization',
            field=models.CharField(choices=[('math', 'math'), ('history', 'history'), ('programming', 'programming'), ('unknown', 'unknown')], max_length=200),
        ),
    ]
